-- ⚠️ OBSOLÈTE - Ne plus utiliser ce fichier.
-- Ce fichier a été remplacé par fix_all_issues.sql qui gère
-- toutes les policies RLS de manière atomique et idempotente.
--
-- Exécutez plutôt: fix_all_issues.sql
-- Ce script inclut les mêmes corrections + index + transaction.