// Villes du Benin avec coordonnees
export const cities = [
  { id: 1, name: 'Banikoara', neighborhoods: ['Banikoara', 'Founougo', 'Gomparou'], lat: 11.3, lng: 2.4 },
  { id: 2, name: 'Gogounou', neighborhoods: ['Gogounou', 'Bagou', 'Gounarou'], lat: 11.5, lng: 2.7 },
  { id: 3, name: 'Kandi', neighborhoods: ['Kandi I', 'Kandi II', 'Kandi III'], lat: 11.13, lng: 2.94 },
  { id: 4, name: 'Karimama', neighborhoods: ['Karimama', 'Birni-Lafia'], lat: 11.8, lng: 3.1 },
  { id: 5, name: 'Malanville', neighborhoods: ['Malanville', 'Garou', 'Guene'], lat: 11.86, lng: 3.23 },
  { id: 6, name: 'Segbana', neighborhoods: ['Segbana', 'Liboussou', 'Lougou'], lat: 10.93, lng: 3.7 },
  { id: 7, name: 'Natitingou', neighborhoods: ['Natitingou I', 'Natitingou II', 'Natitingou III'], lat: 10.3, lng: 1.38 },
  { id: 8, name: 'Tanguieta', neighborhoods: ['Tanguieta', 'Cotiakou', 'Tanongou'], lat: 10.62, lng: 1.07 },
  { id: 9, name: 'Boukoumbe', neighborhoods: ['Boukoumbe', 'Dipoli', 'Korontiere'], lat: 10.05, lng: 1.07 },
  { id: 10, name: 'Kerou', neighborhoods: ['Kerou', 'Brignamaro', 'Firou'], lat: 10.95, lng: 1.55 },
  { id: 11, name: 'Kouande', neighborhoods: ['Kouande', 'Birni', 'Fô-Tance'], lat: 10.65, lng: 1.72 },
  { id: 12, name: 'Materi', neighborhoods: ['Materi', 'Dassari', 'Gouande'], lat: 10.52, lng: 1.33 },
  { id: 13, name: 'Cobly', neighborhoods: ['Cobly', 'Datori', 'Kountori'], lat: 10.38, lng: 1.45 },
  { id: 14, name: 'Pehunco', neighborhoods: ['Pehunco', 'Gnemasson', 'Tobre'], lat: 10.25, lng: 1.65 },
  { id: 15, name: 'Toucountouna', neighborhoods: ['Toucountouna', 'Kouarfa'], lat: 10.47, lng: 1.18 },
  { id: 16, name: 'Abomey-Calavi', neighborhoods: ['Abomey-Calavi', 'Akassato', 'Godomey', 'Glo-Djigbe', 'Hevie', 'Zinvie'], lat: 6.45, lng: 2.35 },
  { id: 17, name: 'Ouidah', neighborhoods: ['Ouidah I', 'Ouidah II', 'Ouidah III', 'Avlekete'], lat: 6.36, lng: 2.08 },
  { id: 18, name: 'Allada', neighborhoods: ['Allada', 'Agbanou', 'Attogon', 'Hinvi'], lat: 6.58, lng: 2.22 },
  { id: 19, name: 'So-Ava', neighborhoods: ['So-Ava', 'Houedo', 'Togba'], lat: 6.51, lng: 2.41 },
  { id: 20, name: 'Toffo', neighborhoods: ['Toffo', 'Kpomasse'], lat: 6.72, lng: 2.15 },
  { id: 21, name: 'Tori-Bossito', neighborhoods: ['Tori', 'Bossito'], lat: 6.25, lng: 2.17 },
  { id: 22, name: 'Kpomasse', neighborhoods: ['Kpomasse'], lat: 6.78, lng: 2.08 },
  { id: 23, name: 'Ze', neighborhoods: ['Ze', 'Djacodji'], lat: 6.62, lng: 2.47 },
  { id: 24, name: 'Parakou', neighborhoods: ['Parakou I', 'Parakou II', 'Parakou III'], lat: 9.34, lng: 2.62 },
  { id: 25, name: 'Bemberere', neighborhoods: ['Bemberere', 'Beroubouay', 'Gamia'], lat: 9.93, lng: 2.69 },
  { id: 26, name: 'Kalale', neighborhoods: ['Kalale', 'Bouca', 'Dekassa'], lat: 9.78, lng: 2.93 },
  { id: 27, name: 'Ndali', neighborhoods: ['Ndali', 'Bori', 'Gbegourou'], lat: 9.72, lng: 2.99 },
  { id: 28, name: 'Nikki', neighborhoods: ['Nikki', 'Biro', 'Sakabansi'], lat: 9.92, lng: 3.21 },
  { id: 29, name: 'Perere', neighborhoods: ['Perere', 'Gninsy', 'Komiguea'], lat: 9.78, lng: 3.35 },
  { id: 30, name: 'Sinende', neighborhoods: ['Sinende', 'Fo-Boure'], lat: 10.11, lng: 2.48 },
  { id: 31, name: 'Tchaourou', neighborhoods: ['Tchaourou', 'Alafiarou', 'Beterou'], lat: 8.89, lng: 2.61 },
  { id: 32, name: 'Dassa-Zoume', neighborhoods: ['Dassa I', 'Dassa II', 'Gbaffo', 'Kpingni'], lat: 7.75, lng: 2.08 },
  { id: 33, name: 'Savalou', neighborhoods: ['Savalou', 'Djloukou', 'Doumè', 'Gobada'], lat: 7.93, lng: 1.97 },
  { id: 34, name: 'Save', neighborhoods: ['Save I', 'Save II', 'Kaboua'], lat: 7.98, lng: 2.49 },
  { id: 35, name: 'Bante', neighborhoods: ['Bante', 'Agoua', 'Atokoligbe'], lat: 7.73, lng: 1.72 },
  { id: 36, name: 'Glazoue', neighborhoods: ['Glazoue', 'Aklankpa', 'Assante'], lat: 7.72, lng: 2.25 },
  { id: 37, name: 'Ouesse', neighborhoods: ['Ouesse', 'Gbanlin', 'Kilibo'], lat: 7.51, lng: 2.47 },
  { id: 38, name: 'Aplahoue', neighborhoods: ['Aplahoue', 'Atome', 'Azove', 'Dekpo'], lat: 6.98, lng: 1.87 },
  { id: 39, name: 'Djakotomey', neighborhoods: ['Djakotomey I', 'Djakotomey II', 'Gohomey'], lat: 6.9, lng: 1.65 },
  { id: 40, name: 'Dogbo', neighborhoods: ['Dogbo', 'Ayomi', 'Devè'], lat: 6.9, lng: 1.78 },
  { id: 41, name: 'Klouekanme', neighborhoods: ['Klouekanme', 'Adjanhonme', 'Ahogbeya'], lat: 7.1, lng: 1.97 },
  { id: 42, name: 'Lalo', neighborhoods: ['Lalo', 'Ahomadegbe', 'Gnizounme'], lat: 6.82, lng: 1.7 },
  { id: 43, name: 'Toviklin', neighborhoods: ['Toviklin', 'Adjido', 'Avedjin'], lat: 6.78, lng: 1.85 },
  { id: 44, name: 'Djougou', neighborhoods: ['Djougou I', 'Djougou II', 'Djougou III', 'Barienou'], lat: 9.7, lng: 1.62 },
  { id: 45, name: 'Bassila', neighborhoods: ['Bassila', 'Alejo', 'Manigri'], lat: 9.0, lng: 1.77 },
  { id: 46, name: 'Copargo', neighborhoods: ['Copargo', 'Anandana', 'Pabegou'], lat: 9.53, lng: 1.43 },
  { id: 47, name: 'Ouake', neighborhoods: ['Ouake', 'Badjoude', 'Komde'], lat: 9.32, lng: 1.41 },
  { id: 48, name: 'Cotonou', neighborhoods: ['Akpakpa', 'Ganhi', 'Fidrosse', 'Menontin', 'Sainte-Rita', 'Agla', 'Missebo', 'Vedoko'], lat: 6.37, lng: 2.39 },
  { id: 49, name: 'Lokossa', neighborhoods: ['Lokossa', 'Agame', 'Houin'], lat: 6.9, lng: 1.97 },
  { id: 50, name: 'Athieme', neighborhoods: ['Athieme', 'Adohoun', 'Atchannou'], lat: 6.6, lng: 1.95 },
  { id: 51, name: 'Bopa', neighborhoods: ['Bopa', 'Agbodji', 'Lobogo'], lat: 6.55, lng: 1.78 },
  { id: 52, name: 'Come', neighborhoods: ['Come', 'Agatogbo', 'Akodeha'], lat: 6.23, lng: 1.87 },
  { id: 53, name: 'Grand-Popo', neighborhoods: ['Grand-Popo', 'Adjaha', 'Avloh'], lat: 6.28, lng: 1.75 },
  { id: 54, name: 'Houeyogbe', neighborhoods: ['Houeyogbe', 'Dahe', 'Honhoue'], lat: 6.43, lng: 1.83 },
  { id: 55, name: 'Seme-Kpodji', neighborhoods: ['Seme-Kpodji', 'Agblangandan'], lat: 6.33, lng: 2.52 },
  { id: 56, name: 'Adjarra', neighborhoods: ['Adjarra I', 'Adjarra II', 'Aglogbe'], lat: 6.55, lng: 2.5 },
  { id: 57, name: 'Adjohoun', neighborhoods: ['Adjohoun', 'Akpadanou', 'Awonou'], lat: 6.68, lng: 2.35 },
  { id: 58, name: 'Aguegues', neighborhoods: ['Avagbodji', 'Houedome'], lat: 6.45, lng: 2.43 },
  { id: 59, name: 'Akpro-Misserete', neighborhoods: ['Akpro-Misserete', 'Gome', 'Katagon'], lat: 6.58, lng: 2.45 },
  { id: 60, name: 'Avrankou', neighborhoods: ['Avrankou', 'Djomon', 'Gbozounme'], lat: 6.72, lng: 2.53 },
  { id: 61, name: 'Bonou', neighborhoods: ['Bonou', 'Affame', 'Atchonsa'], lat: 6.78, lng: 2.25 },
  { id: 62, name: 'Dangbo', neighborhoods: ['Dangbo', 'Dekin', 'Gbeko'], lat: 6.88, lng: 2.48 },
  { id: 63, name: 'Porto-Novo', neighborhoods: ['Centre', 'Haute-Ville', 'Dokpara', 'Nokoue'], lat: 6.5, lng: 2.62 },
  { id: 64, name: 'Ketou', neighborhoods: ['Ketou', 'Adakplame', 'Idigny'], lat: 7.35, lng: 3.08 },
  { id: 65, name: 'Pobe', neighborhoods: ['Pobe', 'Ahoyeye', 'Igana'], lat: 7.45, lng: 2.77 },
  { id: 66, name: 'Sakete', neighborhoods: ['Sakete I', 'Sakete II', 'Aguidi'], lat: 7.42, lng: 2.58 },
  { id: 67, name: 'Ifangni', neighborhoods: ['Ifangni', 'Banigbe', 'Daagbe'], lat: 7.25, lng: 2.45 },
  { id: 68, name: 'Adja-Ouere', neighborhoods: ['Adja-Ouere', 'Ikpinle', 'Koulou'], lat: 7.28, lng: 2.55 },
  { id: 69, name: 'Abomey', neighborhoods: ['Abomey I', 'Abomey II', 'Abomey III', 'Agbokpa'], lat: 7.19, lng: 1.99 },
  { id: 70, name: 'Bohicon', neighborhoods: ['Bohicon I', 'Bohicon II', 'Agongointo'], lat: 7.18, lng: 2.07 },
  { id: 71, name: 'Cove', neighborhoods: ['Cove', 'Adogbe', 'Houen-Hounso'], lat: 7.2, lng: 1.88 },
  { id: 72, name: 'Djidja', neighborhoods: ['Djidja', 'Agondji', 'Agouna', 'Monsourou'], lat: 7.35, lng: 2.08 },
  { id: 73, name: 'Agbangnizoun', neighborhoods: ['Agbangnizoun', 'Adahondjigon', 'Kinta'], lat: 7.08, lng: 1.82 },
  { id: 74, name: 'Ouinhi', neighborhoods: ['Ouinhi', 'Dasso', 'Sagon'], lat: 7.12, lng: 2.25 },
  { id: 75, name: 'Za-Kpota', neighborhoods: ['Za-Kpota', 'Allahé', 'Houngome'], lat: 7.28, lng: 2.18 },
  { id: 76, name: 'Zogbodomey', neighborhoods: ['Zogbodomey', 'Akiza', 'Avlame'], lat: 7.08, lng: 2.28 }
]

// Categories de produits
export const categories = [
  { id: 1, name: 'Electronique', icon: 'smartphone', color: '#FF6A00' },
  { id: 2, name: 'Vêtements', icon: 'shirt', color: '#00A2E8' },
  { id: 3, name: 'Alimentation', icon: 'apple', color: '#00C853' },
  { id: 4, name: 'Maison', icon: 'home', color: '#9C27B0' },
  { id: 5, name: 'Beaute', icon: 'sparkle', color: '#E91E63' },
  { id: 6, name: 'Sports', icon: 'dumbbell', color: '#FF5722' },
  { id: 7, name: 'Jouets', icon: 'gamepad2', color: '#2196F3' },
  { id: 8, name: 'Vehicules', icon: 'car', color: '#607D8B' },
  { id: 9, name: 'Autres', icon: 'package', color: '#9E9E9E' }
]

// Categories de services
export const serviceCategories = [
  { id: 1, name: 'Dépannage', icon: 'wrench', color: '#FF6A00' },
  { id: 2, name: 'Ménage', icon: 'sparkles', color: '#00A2E8' },
  { id: 3, name: 'Beauté', icon: 'scissors', color: '#E91E63' },
  { id: 4, name: 'Informatique', icon: 'laptop', color: '#2196F3' },
  { id: 5, name: 'Cours', icon: 'book', color: '#9C27B0' },
  { id: 6, name: 'Bâtiment', icon: 'home', color: '#795548' },
  { id: 7, name: 'Transport', icon: 'truck', color: '#607D8B' },
  { id: 8, name: 'Événementiel', icon: 'music', color: '#FF5722' },
  { id: 9, name: 'Autres Services', icon: 'briefcase', color: '#9E9E9E' }
]
